export * from './aVIS.service';
import { AVISService } from './aVIS.service';
export * from './anterogradia.service';
import { AnterogradiaService } from './anterogradia.service';
export * from './resources.service';
import { ResourcesService } from './resources.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './tangentialAuth.service';
import { TangentialAuthService } from './tangentialAuth.service';
export * from './tangentialAuxiliary.service';
import { TangentialAuxiliaryService } from './tangentialAuxiliary.service';
export * from './tangentialContent.service';
import { TangentialContentService } from './tangentialContent.service';
export * from './topics.service';
import { TopicsService } from './topics.service';
export const APIS = [AVISService, AnterogradiaService, ResourcesService, StatusService, TangentialAuthService, TangentialAuxiliaryService, TangentialContentService, TopicsService];
