/**
 * Medaware Catalyst
 * The API Specification for Medaware
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ElementTypeRequirement { 
    type: string;
    requirements: Array<string>;
}

