/**
 * Medaware Catalyst
 * The API Specification for Medaware
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestGHS200ResponseScoresInner } from './requestGHS200ResponseScoresInner';


export interface RequestGHS200Response { 
    output: string;
    scores: Array<RequestGHS200ResponseScoresInner>;
}

