/**
 * Medaware Catalyst
 * The API Specification for Medaware
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestGHS200ResponseScoresInner { 
    _class: string;
    score: number;
}

